/* Generated by Yosys 0.4 (git sha1 d5aa0ee, gcc 4.8.2-19ubuntu1 -O2 -fstack-protector -fPIC -Os) */

(* src = "fullAdder.v:7" *)
module fullAdder(A, B, C, S, CO);
  (* src = "fullAdder.v:8" *)
  input A;
  (* src = "fullAdder.v:8" *)
  input B;
  (* src = "fullAdder.v:8" *)
  input C;
  (* src = "fullAdder.v:9" *)
  output S;
  (* src = "fullAdder.v:9" *)
  output CO;
  (* src = "fullAdder.v:10" *)
  wire w1;
  (* src = "fullAdder.v:10" *)
  wire w2;
  (* src = "fullAdder.v:10" *)
  wire w3;
  (* src = "fullAdder.v:12" *)
  wire _0_;
  (* src = "fullAdder.v:13" *)
  wire _1_;
  (* src = "fullAdder.v:15" *)
  wire _2_;
  (* src = "fullAdder.v:16" *)
  wire _3_;
  (* src = "fullAdder.v:18" *)
  wire _4_;
  assign _0_ = A ^ (* src = "fullAdder.v:12" *) B;
  assign _1_ = w1 ^ (* src = "fullAdder.v:13" *) CO;
  assign _2_ = C & (* src = "fullAdder.v:15" *) w1;
  assign _3_ = A & (* src = "fullAdder.v:16" *) B;
  assign _4_ = w1 | (* src = "fullAdder.v:18" *) w2;
  assign w1 = _0_;
  assign S = _1_;
  assign w2 = _2_;
  assign w3 = _3_;
  assign CO = _4_;
endmodule
