/* Generated by Yosys 0.4+28 (git sha1 032511f, gcc 4.8.2-19ubuntu1 -fPIC -Os) */

(* src = "fabehav.v:7" *)
module fa(A, B, C, S, SUM, CO);
  (* src = "fabehav.v:8" *)
  input A;
  (* src = "fabehav.v:8" *)
  input B;
  (* src = "fabehav.v:8" *)
  input C;
  (* src = "fabehav.v:8" *)
  input S;
  (* src = "fabehav.v:9" *)
  output SUM;
  (* src = "fabehav.v:9" *)
  output CO;
  (* src = "fabehav.v:11" *)
  wire [1:0] _0_;
  (* src = "fabehav.v:11" *)
  wire [1:0] _1_;
  assign _0_ = A + (* src = "fabehav.v:11" *) B;
  assign _1_ = A + (* src = "fabehav.v:11" *) C;
  assign { CO, SUM } = S ? (* src = "fabehav.v:11" *) _0_ : _1_;
endmodule
